[
  { country_code: :cn, calendar_type: :gregorian, en_name: "New Year", ja_name: "New Year", expression: "1.1" },
  { country_code: :cn, calendar_type: :julian, en_name: "Chinese New Year", ja_name: "Chinese New Year", expression: "(12.31)-(1.6)" },
  { country_code: :cn, calendar_type: :gregorian, en_name: "Labor Day", ja_name: "Labor Day", expression: "5.1" },
  { country_code: :cn, calendar_type: :julian, en_name: "Dragon Boat Festival", ja_name: "Dragon Boat Festival", expression: "5.5" },
  { country_code: :cn, calendar_type: :julian, en_name: "Mid Autumn or Moon Festival", ja_name: "Mid Autumn or Moon Festival", expression: "8.15" },
  { country_code: :cn, calendar_type: :gregorian, en_name: "National Day ", ja_name: "National Day ", expression: "10.1-7" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "New Year", ja_name: "New Year", expression: "1.1" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "Coming of Age Day", ja_name: "Coming of Age Day", expression: "1.2,1" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "Foundation Day", ja_name: "Foundation Day", expression: "2.11" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "Showa Day", ja_name: "Showa Day", expression: "4.29" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "Constitution Memorial Day", ja_name: "Constitution Memorial Day", expression: "5.3" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "Greenery Day", ja_name: "Greenery Day", expression: "5.4" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "Children's Day", ja_name: "Children's Day", expression: "5.5" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "Marine Day", ja_name: "Marine Day", expression: "7.3,1" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "Mountain Day", ja_name: "Mountain Day", expression: "8.11" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "Respect-for-the-Aged Day", ja_name: "Respect-for-the-Aged Day", expression: "9.3,1" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "Health and Sports Day", ja_name: "Health and Sports Day", expression: "10.2,1" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "Culture Day", ja_name: "Culture Day", expression: "11.3" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "Labor Thanksgiving Day", ja_name: "Labor Thanksgiving Day", expression: "11.23" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "The Emperor’s Birthday", ja_name: "The Emperor’s Birthday", expression: "12.23" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "New Year's Eve", ja_name: "New Year's Eve", expression: "12.31" },
  { country_code: :kr, calendar_type: :gregorian, en_name: "New Year", ja_name: "New Year", expression: "1.1" },
  { country_code: :kr, calendar_type: :julian, en_name: "krn New Year", ja_name: "krn New Year", expression: "(12.31)-(1.2)" },
  { country_code: :kr, calendar_type: :gregorian, en_name: "March First Movement", ja_name: "March First Movement", expression: "3.1" },
  { country_code: :kr, calendar_type: :gregorian, en_name: "Children's Day", ja_name: "Children's Day", expression: "5.5" },
  { country_code: :kr, calendar_type: :julian, en_name: "Buddha Birthday", ja_name: "Buddha Birthday", expression: "4.8" },
  { country_code: :kr, calendar_type: :gregorian, en_name: "South kr Memorial Day", ja_name: "South kr Memorial Day", expression: "6.6" },
  { country_code: :kr, calendar_type: :gregorian, en_name: "Liberation Day", ja_name: "Liberation Day", expression: "8.15" },
  { country_code: :kr, calendar_type: :julian, en_name: "Chuseok", ja_name: "Chuseok", expression: "8.14-16" },
  { country_code: :kr, calendar_type: :gregorian, en_name: "National  Day", ja_name: "National  Day", expression: "10.3" },
  { country_code: :kr, calendar_type: :gregorian, en_name: "Hangul Day", ja_name: "Hangul Day", expression: "10.9" },
  { country_code: :kr, calendar_type: :gregorian, en_name: "Christmas Day", ja_name: "Christmas Day", expression: "12.25" },
  { country_code: :tw, calendar_type: :gregorian, en_name: "New Years Day", ja_name: "New Years Day", expression: "1.1" },
  { country_code: :tw, calendar_type: :julian, en_name: "Chinese New Year", ja_name: "Chinese New Year", expression: "(12.31)-(1.3)" },
  { country_code: :tw, calendar_type: :gregorian, en_name: "Peace Memorial Day", ja_name: "Peace Memorial Day", expression: "2.28" },
  { country_code: :tw, calendar_type: :gregorian, en_name: "Children Day", ja_name: "Children Day", expression: "4.4" },
  { country_code: :tw, calendar_type: :gregorian, en_name: "Labor Day", ja_name: "Labor Day", expression: "5.1" },
  { country_code: :tw, calendar_type: :julian, en_name: "Dragon Boat Festival", ja_name: "Dragon Boat Festival", expression: "5.5" },
  { country_code: :tw, calendar_type: :julian, en_name: "Mid Autumn or Moon Festival", ja_name: "Mid Autumn or Moon Festival", expression: "8.15" },
  { country_code: :tw, calendar_type: :gregorian, en_name: "National Day", ja_name: "National Day", expression: "10.10" },
  { country_code: :th, calendar_type: :gregorian, en_name: "New Year", ja_name: "New Year", expression: "1.1" },
  { country_code: :th, calendar_type: :gregorian, en_name: "Chakri Memorial Day", ja_name: "Chakri Memorial Day", expression: "4.6" },
  { country_code: :th, calendar_type: :gregorian, en_name: "Songkran Festival", ja_name: "Songkran Festival", expression: "4.13-15" },
  { country_code: :th, calendar_type: :gregorian, en_name: "Labor Day", ja_name: "Labor Day", expression: "5.1" },
  { country_code: :th, calendar_type: :gregorian, en_name: "King's Birthday", ja_name: "King's Birthday", expression: "7.28" },
  { country_code: :th, calendar_type: :gregorian, en_name: "Queen's Birthday", ja_name: "Queen's Birthday", expression: "8.12" },
  { country_code: :th, calendar_type: :gregorian, en_name: "King Rama IX's Death", ja_name: "King Rama IX's Death", expression: "10.13" },
  { country_code: :th, calendar_type: :gregorian, en_name: "Chulalongkorn Day", ja_name: "Chulalongkorn Day", expression: "10.23" },
  { country_code: :th, calendar_type: :gregorian, en_name: "King Rama IX's Birthday Birthday", ja_name: "King Rama IX's Birthday Birthday", expression: "12.5" },
  { country_code: :th, calendar_type: :gregorian, en_name: "Constitution Day", ja_name: "Constitution Day", expression: "12.10" },
  { country_code: :th, calendar_type: :gregorian, en_name: "New Year's Eve", ja_name: "New Year's Eve", expression: "12.31" },
  { country_code: :th, calendar_type: :julian, en_name: "Makha Bucha Day", ja_name: "Makha Bucha Day", expression: "3.full-moon" },
  { country_code: :th, calendar_type: :julian, en_name: "Visakha Bucha Day", ja_name: "Visakha Bucha Day", expression: "7.full-moon" },
  { country_code: :th, calendar_type: :julian, en_name: "Asalha Bucha", ja_name: "Asalha Bucha", expression: "8.full-moon" },
  { country_code: :th, calendar_type: :julian, en_name: "Buddhist Lent Day", ja_name: "Buddhist Lent Day", expression: "8.full-moon(+1)" },
  { country_code: :us, calendar_type: :gregorian, en_name: "New Year", ja_name: "New Year", expression: "1.1" },
  { country_code: :us, calendar_type: :gregorian, en_name: "Martin Luther King Jr.'S Birthday", ja_name: "Martin Luther King Jr.'S Birthday", expression: "1.3,1" },
  { country_code: :us, calendar_type: :gregorian, en_name: "President's Day", ja_name: "President's Day", expression: "2.3,1" },
  { country_code: :us, calendar_type: :gregorian, en_name: "Memorial Day", ja_name: "Memorial Day", expression: "5.-1,1" },
  { country_code: :us, calendar_type: :gregorian, en_name: "Independence Day", ja_name: "Independence Day", expression: "7.4" },
  { country_code: :us, calendar_type: :gregorian, en_name: "Labor Day", ja_name: "Labor Day", expression: "9.1,1" },
  { country_code: :us, calendar_type: :gregorian, en_name: "Columbus Day", ja_name: "Columbus Day", expression: "10.2,1" },
  { country_code: :us, calendar_type: :gregorian, en_name: "Veterans Day", ja_name: "Veterans Day", expression: "11.11" },
  { country_code: :us, calendar_type: :gregorian, en_name: "Thanksgiving Day", ja_name: "Thanksgiving Day", expression: "11.4,1" },
  { country_code: :us, calendar_type: :gregorian, en_name: "Christmas Day", ja_name: "Christmas Day", expression: "12.25" }
].each do |attrs|
  HolidayExpr.find_or_create_by(attrs).generate_holidays
end