# rubocop:disable Metrics/LineLength
[
  { country_code: :cn, calendar_type: :gregorian, en_name: "New Year", ja_name: "元旦", expression: "1.1" },
  { country_code: :cn, calendar_type: :julian, en_name: "Chinese New Year", ja_name: "春節", expression: "(12.31)-(1.6)" },
  { country_code: :cn, calendar_type: :gregorian, en_name: "Labor Day", ja_name: "労働節", expression: "5.1" },
  { country_code: :cn, calendar_type: :julian, en_name: "Dragon Boat Festival", ja_name: "端午節", expression: "5.5" },
  { country_code: :cn, calendar_type: :julian, en_name: "Mid Autumn or Moon Festival", ja_name: "中秋節", expression: "8.15" },
  { country_code: :cn, calendar_type: :gregorian, en_name: "National Day ", ja_name: "国慶節", expression: "10.1-7" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "New Year", ja_name: "元旦", expression: "1.1" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "Coming of Age Day", ja_name: "成人の日", expression: "1.2,1" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "Foundation Day", ja_name: "建国記念の日", expression: "2.11" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "Showa Day", ja_name: "昭和の日", expression: "4.29" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "Constitution Memorial Day", ja_name: "憲法記念日", expression: "5.3" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "Greenery Day", ja_name: "みどりの日", expression: "5.4" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "Children's Day", ja_name: "子供の日", expression: "5.5" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "Marine Day", ja_name: "海の日", expression: "7.3,1" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "Mountain Day", ja_name: "山の日", expression: "8.11" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "Respect-for-the-Aged Day", ja_name: "敬老の日", expression: "9.3,1" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "Health and Sports Day", ja_name: "体育の日", expression: "10.2,1" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "Culture Day", ja_name: "文化の日", expression: "11.3" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "Labor Thanksgiving Day", ja_name: "勤労感謝の日", expression: "11.23" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "The Emperor’s Birthday", ja_name: " 天皇誕生日", expression: "12.23" },
  { country_code: :jp, calendar_type: :gregorian, en_name: "New Year's Eve", ja_name: "大晦日", expression: "12.31" },
  { country_code: :kr, calendar_type: :gregorian, en_name: "New Year", ja_name: "元旦", expression: "1.1" },
  { country_code: :kr, calendar_type: :julian, en_name: "Korean New Year", ja_name: "Korean New Year", expression: "(12.31)-(1.2)" },
  { country_code: :kr, calendar_type: :gregorian, en_name: "March First Movement", ja_name: "三一節", expression: "3.1" },
  { country_code: :kr, calendar_type: :gregorian, en_name: "Children's Day", ja_name: "子どもの日", expression: "5.5" },
  { country_code: :kr, calendar_type: :julian, en_name: "Buddha Birthday", ja_name: "仏誕節", expression: "4.8" },
  { country_code: :kr, calendar_type: :gregorian, en_name: "South Korea Memorial Day", ja_name: "South Korea Memorial Day", expression: "6.6" },
  { country_code: :kr, calendar_type: :gregorian, en_name: "Liberation Day", ja_name: "光復節", expression: "8.15" },
  { country_code: :kr, calendar_type: :julian, en_name: "Chuseok", ja_name: "秋夕", expression: "8.14-16" },
  { country_code: :kr, calendar_type: :gregorian, en_name: "National  Day", ja_name: "開天節", expression: "10.3" },
  { country_code: :kr, calendar_type: :gregorian, en_name: "Hangul Day", ja_name: "ハングルの日", expression: "10.9" },
  { country_code: :kr, calendar_type: :gregorian, en_name: "Christmas Day", ja_name: "クリスマス", expression: "12.25" },
  { country_code: :tw, calendar_type: :gregorian, en_name: "New Years Day", ja_name: "旧正月", expression: "1.1" },
  { country_code: :tw, calendar_type: :julian, en_name: "Chinese New Year", ja_name: "和平記念日", expression: "(12.31)-(1.3)" },
  { country_code: :tw, calendar_type: :gregorian, en_name: "Peace Memorial Day", ja_name: "子どもの日", expression: "2.28" },
  { country_code: :tw, calendar_type: :gregorian, en_name: "Children Day", ja_name: "Children Day", expression: "4.4" },
  { country_code: :tw, calendar_type: :gregorian, en_name: "Labor Day", ja_name: "端午節", expression: "5.1" },
  { country_code: :tw, calendar_type: :julian, en_name: "Dragon Boat Festival", ja_name: "中秋節", expression: "5.5" },
  { country_code: :tw, calendar_type: :julian, en_name: "Mid Autumn or Moon Festival", ja_name: "国慶日", expression: "8.15" },
  { country_code: :tw, calendar_type: :gregorian, en_name: "National Day", ja_name: "元旦", expression: "10.10" },
  { country_code: :th, calendar_type: :gregorian, en_name: "New Year", ja_name: "元旦", expression: "1.1" },
  { country_code: :th, calendar_type: :gregorian, en_name: "Chakri Memorial Day", ja_name: "チャックリー記念日", expression: "4.6" },
  { country_code: :th, calendar_type: :gregorian, en_name: "Songkran Festival", ja_name: "ソンクラーン（旧正月）", expression: "4.13-15" },
  { country_code: :th, calendar_type: :gregorian, en_name: "Labor Day", ja_name: "Labor Day", expression: "5.1" },
  { country_code: :th, calendar_type: :gregorian, en_name: "King's Birthday", ja_name: "王妃誕生日", expression: "7.28" },
  { country_code: :th, calendar_type: :gregorian, en_name: "Queen's Birthday", ja_name: "王妃誕生日", expression: "8.12" },
  { country_code: :th, calendar_type: :gregorian, en_name: "King Rama IX's Death", ja_name: "ラマ９世崩御日", expression: "10.13" },
  { country_code: :th, calendar_type: :gregorian, en_name: "Chulalongkorn Day", ja_name: "チュラロコーン大王記念日", expression: "10.23" },
  { country_code: :th, calendar_type: :gregorian, en_name: "King Rama IX's Birthday Birthday", ja_name: "ラーマ9世記念日", expression: "12.5" },
  { country_code: :th, calendar_type: :gregorian, en_name: "Constitution Day", ja_name: "憲法記念日", expression: "12.10" },
  { country_code: :th, calendar_type: :gregorian, en_name: "New Year's Eve", ja_name: "大晦日", expression: "12.31" },
  { country_code: :th, calendar_type: :julian, en_name: "Makha Bucha Day", ja_name: "万仏祭", expression: "3.full-moon" },
  { country_code: :th, calendar_type: :julian, en_name: "Visakha Bucha Day", ja_name: "仏誕節", expression: "7.full-moon" },
  { country_code: :th, calendar_type: :julian, en_name: "Asalha Bucha", ja_name: "三宝節", expression: "8.full-moon" },
  { country_code: :th, calendar_type: :julian, en_name: "Buddhist Lent Day", ja_name: "入安居", expression: "8.full-moon(+1)" },
  { country_code: :us, calendar_type: :gregorian, en_name: "New Year", ja_name: "元旦", expression: "1.1" },
  { country_code: :us, calendar_type: :gregorian, en_name: "Martin Luther King Jr.'S Birthday", ja_name: "マーティン・ルーサー・キング誕生日", expression: "1.3,1" },
  { country_code: :us, calendar_type: :gregorian, en_name: "President's Day", ja_name: "大統領の日", expression: "2.3,1" },
  { country_code: :us, calendar_type: :gregorian, en_name: "Memorial Day", ja_name: "戦没者祈念日", expression: "5.-1,1" },
  { country_code: :us, calendar_type: :gregorian, en_name: "Independence Day", ja_name: "Independence Day", expression: "7.4" },
  { country_code: :us, calendar_type: :gregorian, en_name: "Labor Day", ja_name: " 労働感謝の日", expression: "9.1,1" },
  { country_code: :us, calendar_type: :gregorian, en_name: "Columbus Day", ja_name: "コロンブス記念日", expression: "10.2,1" },
  { country_code: :us, calendar_type: :gregorian, en_name: "Veterans Day", ja_name: "退役軍人の日", expression: "11.11" },
  { country_code: :us, calendar_type: :gregorian, en_name: "Thanksgiving Day", ja_name: "感謝祭", expression: "11.4,1" },
  { country_code: :us, calendar_type: :gregorian, en_name: "Christmas Day", ja_name: "クリスマス", expression: "12.25" }
].each do |attrs|
  HolidayExpr.find_or_create_by(attrs).generate_holidays
end

# rubocop:enable Metrics/LineLength
