default: &default
  adapter:  <%= ENV.fetch('DB_ADAPTER', 'postgresql') %>
  username: <%= ENV.fetch('DB_USER', 'postgres') %>
  port: <%= ENV.fetch('DB_PORT', 5432) %>
  host: <%= ENV.fetch('DB_HOST', '127.0.0.1') %>
  password: <%= ENV.fetch('DB_PASSWORD', '') %>

development:
  <<: *default
  database: holidays_development
  pool:     10

test:
  <<: *default
  database: holidays_test
  pool:     10

production:
  <<: *default
  database: holidays_production
  pool:     10

staging:
  <<: *default
  database: holidays_staging
  pool:     10
