version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ./backend/:/home/dockeruser/project
      - gems:/usr/local/bundle
    links:
      - mysql
      - frontend
    ports:
      - 3000:3000
    env_file: .env
    stdin_open: true
    tty: true

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    environment:
      HOST: '0.0.0.0'
      PORT: '8080'
    volumes:
      - ./frontend:/home/dockeruser/project
      - node_modules:/home/dockeruser/project/node_modules
    ports:
      - 8080:8080
    env_file: .env
    stdin_open: true
    tty: true

  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    env_file: .env
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    ports:
      - 3306:3306
    volumes:
      - ./backend:/home/root/project
      - ./docker/mysql/data:/var/lib/mysql

volumes:
  gems:
  node_modules:
