version: '3'
services:
  backend:
    image: holidays-api_backend
    build:
      context: .
      dockerfile: docker/back/Dockerfile
      target: back-dev  # back-deploy
    volumes:
      - ./backend:/home/dockeruser/project
      - gems:/usr/local/bundle
    links:
      # - postgres
      - frontend
    ports:
      - 3000:3000
    env_file: .env
    stdin_open: true
    tty: true

  frontend:
    image: holidays-api_frontend
    build:
      context: .
      dockerfile: docker/front/Dockerfile
      target: front-dev  # front-deploy
    environment:
      HOST: '0.0.0.0'
      PORT: '8080'
    volumes:
      - ./frontend:/home/dockeruser/project
      - node_modules:/home/dockeruser/project/node_modules
    ports:
      - 8080:8080
    env_file: .env
    stdin_open: true
    tty: true

  # postgres:
  #   build:
  #     context: .
  #     dockerfile: ./docker/postgresql/Dockerfile
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./docker/postgresql/data/:/var/lib/postgresql/data

volumes:
  gems:
  node_modules:
