version: '3'
services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: ./docker/web/Dockerfile
  #   volumes:
  #     - ./:/home/dockeruser/project
  #     - gems:/usr/local/bundle
  #   links:
  #     - redis
  #     - mysql
  #   ports:
  #     - 3000:3000
  #   env_file: .env
  #   stdin_open: true
  #   tty: true

  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    env_file: .env
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    ports:
      - 3306:3306
    volumes:
      - ./:/home/root/project
      - ./docker/mysql/data:/var/lib/mysql

  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    ports:
      - 6379:6379

volumes:
  gems:
