development:
  adapter:  mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  database: holidays_development
  pool:     10
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] || 'pass' %>
  port: <%= ENV['MYSQL_PORT'] || 3306 %>
  host: <%= ENV['MYSQL_HOST'] || '127.0.0.1'%>

test:
  adapter:  mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  database: holidays_test
  pool:     5
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] || 'pass' %>
  port: <%= ENV['MYSQL_PORT'] || 3306 %>
  host: <%= ENV['MYSQL_HOST'] || '127.0.0.1'%>

production:
  adapter:  mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  database: holidays_production
  pool:     5
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  port: <%= ENV['MYSQL_PORT'] %>
  host: <%= ENV['MYSQL_HOST'] %>
